[package]
name = "test-toml"
version = "0.2.0-alpha.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
toml = "0.7"
serde = "1.0"
serde_derive = "1.0"
