[package]
name = "run-command-ubuntu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
systemctl = "0.1"
roxy = { path = "/Users/dkpark/work/aice/roxy" }
