[package]
name = "test_toml_edit_crate"
version = "0.2.0-alpha.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml_edit="0.19"
